### ISSUE TITLE
A report is created for every test files in the suite

### ISSUE THREAD

**Issue by ultima-forsan** [fijijavis/wdio-json-reporter#10] opened 2017-03-29 15:27 UTC
I have added json reporter to my my configuration file

`reporters: ['dot', 'json'],
    reporterOptions: {
        outputDir: './reports',
        combined: true
    }`

The problem is, for every test files that I have in my suite, a report will be created. When I run a suite with 50 test files, I will have 50 reports! I tried to combine them all together with the `combined: true` but it didn't work.

The expected behaviour would be to only have one report for the whole suite.

The issue is similar to [https://github.com/webdriverio/wdio-spec-reporter/issues/6](url) but was never created here.

**Comment by Bubbit** [comment] 2017-04-06 05:51
The current behaviour of the combined functionality is to result in one extra combined json, intended for CI purposes.

**Comment by fijijavis** [comment] 2017-04-06 12:35
I think we should consider making this an either/or option.  If combined is true then you only get the single file,  If combined is false then you only get the individual files.  I'm on vacation through next Wednesday 04/11 so I'll check it out when I get back.

**Comment by ultima-forsan** [comment] 2017-04-20 14:57
I agree with you @fijijavis . It seems to be the way to go.

Thanks!

**Comment by fijijavis** [comment] 2017-05-04 11:17
@ultima-forsan 
Finally got a chance to look at this.  I am only getting a single combined file when I use 
```
combined:true,
filename:wdio-results
```
I'm closing this unless you have specific steps to reproduce.

**Closed by fijijavis** 2017-05-04 11:17 UTC
